<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldFormSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('field_form')->upsert([
            // Form 1 — Groep 1: Algemeen
            ['id' => 1,   'field_id' => 1,   'field_group_id' => 1,  'form_id' => 1, 'position' => 2,   'required' => 0],
            ['id' => 2,   'field_id' => 2,   'field_group_id' => 1,  'form_id' => 1, 'position' => 3,   'required' => 0],
            ['id' => 3,   'field_id' => 3,   'field_group_id' => 1,  'form_id' => 1, 'position' => 4,   'required' => 0],
            ['id' => 4,   'field_id' => 4,   'field_group_id' => 1,  'form_id' => 1, 'position' => 5,   'required' => 0],
            ['id' => 5,   'field_id' => 5,   'field_group_id' => 1,  'form_id' => 1, 'position' => 6,   'required' => 0],
            ['id' => 6,   'field_id' => 6,   'field_group_id' => 1,  'form_id' => 1, 'position' => 7,   'required' => 0],
            ['id' => 77,  'field_id' => 60,  'field_group_id' => 1,  'form_id' => 1, 'position' => 8,   'required' => 0],
            ['id' => 7,   'field_id' => 7,   'field_group_id' => 1,  'form_id' => 1, 'position' => 9,   'required' => 0],
            ['id' => 8,   'field_id' => 8,   'field_group_id' => 1,  'form_id' => 1, 'position' => 10,  'required' => 0],
            // Form 1 — Groep 2: Toegangen
            ['id' => 9,   'field_id' => 9,   'field_group_id' => 2,  'form_id' => 1, 'position' => 12,  'required' => 0],
            ['id' => 10,  'field_id' => 10,  'field_group_id' => 2,  'form_id' => 1, 'position' => 13,  'required' => 0],
            ['id' => 11,  'field_id' => 11,  'field_group_id' => 2,  'form_id' => 1, 'position' => 14,  'required' => 0],
            ['id' => 12,  'field_id' => 12,  'field_group_id' => 2,  'form_id' => 1, 'position' => 15,  'required' => 0],
            ['id' => 13,  'field_id' => 13,  'field_group_id' => 2,  'form_id' => 1, 'position' => 16,  'required' => 0],
            ['id' => 14,  'field_id' => 14,  'field_group_id' => 2,  'form_id' => 1, 'position' => 17,  'required' => 0],
            // Form 1 — Groep 3: Bedieningsplaatsen
            ['id' => 15,  'field_id' => 15,  'field_group_id' => 3,  'form_id' => 1, 'position' => 19,  'required' => 0],
            ['id' => 16,  'field_id' => 16,  'field_group_id' => 3,  'form_id' => 1, 'position' => 20,  'required' => 0],
            ['id' => 17,  'field_id' => 17,  'field_group_id' => 3,  'form_id' => 1, 'position' => 21,  'required' => 0],
            ['id' => 18,  'field_id' => 18,  'field_group_id' => 3,  'form_id' => 1, 'position' => 22,  'required' => 0],
            ['id' => 19,  'field_id' => 19,  'field_group_id' => 3,  'form_id' => 1, 'position' => 23,  'required' => 0],
            ['id' => 20,  'field_id' => 20,  'field_group_id' => 3,  'form_id' => 1, 'position' => 24,  'required' => 0],
            ['id' => 21,  'field_id' => 21,  'field_group_id' => 3,  'form_id' => 1, 'position' => 25,  'required' => 0],
            ['id' => 22,  'field_id' => 22,  'field_group_id' => 3,  'form_id' => 1, 'position' => 26,  'required' => 0],
            ['id' => 23,  'field_id' => 23,  'field_group_id' => 3,  'form_id' => 1, 'position' => 27,  'required' => 0],
            ['id' => 24,  'field_id' => 24,  'field_group_id' => 3,  'form_id' => 1, 'position' => 28,  'required' => 0],
            ['id' => 25,  'field_id' => 25,  'field_group_id' => 3,  'form_id' => 1, 'position' => 29,  'required' => 0],
            ['id' => 26,  'field_id' => 26,  'field_group_id' => 3,  'form_id' => 1, 'position' => 30,  'required' => 0],
            ['id' => 27,  'field_id' => 27,  'field_group_id' => 3,  'form_id' => 1, 'position' => 31,  'required' => 0],
            ['id' => 28,  'field_id' => 28,  'field_group_id' => 3,  'form_id' => 1, 'position' => 32,  'required' => 0],
            ['id' => 29,  'field_id' => 29,  'field_group_id' => 3,  'form_id' => 1, 'position' => 33,  'required' => 0],
            ['id' => 30,  'field_id' => 30,  'field_group_id' => 3,  'form_id' => 1, 'position' => 34,  'required' => 0],
            ['id' => 31,  'field_id' => 31,  'field_group_id' => 3,  'form_id' => 1, 'position' => 35,  'required' => 0],
            // Form 1 — Groep 6: Gieksysteem
            ['id' => 52,  'field_id' => 35,  'field_group_id' => 6,  'form_id' => 1, 'position' => 37,  'required' => 0],
            ['id' => 53,  'field_id' => 36,  'field_group_id' => 6,  'form_id' => 1, 'position' => 38,  'required' => 0],
            ['id' => 54,  'field_id' => 37,  'field_group_id' => 6,  'form_id' => 1, 'position' => 39,  'required' => 0],
            ['id' => 55,  'field_id' => 38,  'field_group_id' => 6,  'form_id' => 1, 'position' => 40,  'required' => 0],
            ['id' => 56,  'field_id' => 39,  'field_group_id' => 6,  'form_id' => 1, 'position' => 41,  'required' => 0],
            ['id' => 57,  'field_id' => 40,  'field_group_id' => 6,  'form_id' => 1, 'position' => 42,  'required' => 0],
            ['id' => 58,  'field_id' => 41,  'field_group_id' => 6,  'form_id' => 1, 'position' => 43,  'required' => 0],
            // Form 1 — Groep 7: A-Frame / sprenkel
            ['id' => 59,  'field_id' => 42,  'field_group_id' => 7,  'form_id' => 1, 'position' => 45,  'required' => 0],
            ['id' => 60,  'field_id' => 43,  'field_group_id' => 7,  'form_id' => 1, 'position' => 46,  'required' => 0],
            ['id' => 61,  'field_id' => 44,  'field_group_id' => 7,  'form_id' => 1, 'position' => 47,  'required' => 0],
            // Form 1 — Groep 8: Loopkat
            ['id' => 62,  'field_id' => 45,  'field_group_id' => 8,  'form_id' => 1, 'position' => 49,  'required' => 0],
            ['id' => 63,  'field_id' => 46,  'field_group_id' => 8,  'form_id' => 1, 'position' => 50,  'required' => 0],
            ['id' => 64,  'field_id' => 47,  'field_group_id' => 8,  'form_id' => 1, 'position' => 51,  'required' => 0],
            ['id' => 65,  'field_id' => 48,  'field_group_id' => 8,  'form_id' => 1, 'position' => 52,  'required' => 0],
            ['id' => 66,  'field_id' => 49,  'field_group_id' => 8,  'form_id' => 1, 'position' => 53,  'required' => 0],
            ['id' => 67,  'field_id' => 50,  'field_group_id' => 8,  'form_id' => 1, 'position' => 54,  'required' => 0],
            ['id' => 68,  'field_id' => 51,  'field_group_id' => 8,  'form_id' => 1, 'position' => 55,  'required' => 0],
            ['id' => 69,  'field_id' => 52,  'field_group_id' => 8,  'form_id' => 1, 'position' => 56,  'required' => 0],
            // Form 1 — Groep 9: Toren- / torenspits
            ['id' => 70,  'field_id' => 53,  'field_group_id' => 9,  'form_id' => 1, 'position' => 58,  'required' => 0],
            ['id' => 71,  'field_id' => 54,  'field_group_id' => 9,  'form_id' => 1, 'position' => 59,  'required' => 0],
            ['id' => 72,  'field_id' => 55,  'field_group_id' => 9,  'form_id' => 1, 'position' => 60,  'required' => 0],
            ['id' => 73,  'field_id' => 56,  'field_group_id' => 9,  'form_id' => 1, 'position' => 61,  'required' => 0],
            ['id' => 74,  'field_id' => 57,  'field_group_id' => 9,  'form_id' => 1, 'position' => 62,  'required' => 0],
            ['id' => 75,  'field_id' => 58,  'field_group_id' => 9,  'form_id' => 1, 'position' => 63,  'required' => 0],
            ['id' => 76,  'field_id' => 59,  'field_group_id' => 9,  'form_id' => 1, 'position' => 64,  'required' => 0],
            // Form 1 — Groep 10: Zwenkinrichting
            ['id' => 83,  'field_id' => 66,  'field_group_id' => 10, 'form_id' => 1, 'position' => 66,  'required' => 0],
            ['id' => 84,  'field_id' => 67,  'field_group_id' => 10, 'form_id' => 1, 'position' => 67,  'required' => 0],
            ['id' => 85,  'field_id' => 68,  'field_group_id' => 10, 'form_id' => 1, 'position' => 68,  'required' => 0],
            ['id' => 86,  'field_id' => 69,  'field_group_id' => 10, 'form_id' => 1, 'position' => 69,  'required' => 0],
            ['id' => 87,  'field_id' => 70,  'field_group_id' => 10, 'form_id' => 1, 'position' => 70,  'required' => 0],
            ['id' => 88,  'field_id' => 71,  'field_group_id' => 10, 'form_id' => 1, 'position' => 71,  'required' => 0],
            ['id' => 89,  'field_id' => 72,  'field_group_id' => 10, 'form_id' => 1, 'position' => 72,  'required' => 0],
            // Form 1 — Groep 5: Lierwerk
            ['id' => 51,  'field_id' => 34,  'field_group_id' => 5,  'form_id' => 1, 'position' => 74,  'required' => 0],
            ['id' => 50,  'field_id' => 33,  'field_group_id' => 5,  'form_id' => 1, 'position' => 75,  'required' => 0],
            ['id' => 90,  'field_id' => 73,  'field_group_id' => 5,  'form_id' => 1, 'position' => 76,  'required' => 0],
            ['id' => 91,  'field_id' => 74,  'field_group_id' => 5,  'form_id' => 1, 'position' => 77,  'required' => 0],
            ['id' => 92,  'field_id' => 75,  'field_group_id' => 5,  'form_id' => 1, 'position' => 78,  'required' => 0],
            ['id' => 93,  'field_id' => 76,  'field_group_id' => 5,  'form_id' => 1, 'position' => 79,  'required' => 0],
            ['id' => 94,  'field_id' => 77,  'field_group_id' => 5,  'form_id' => 1, 'position' => 80,  'required' => 0],
            ['id' => 95,  'field_id' => 78,  'field_group_id' => 5,  'form_id' => 1, 'position' => 81,  'required' => 0],
            // Form 1 — Groep 11: Kabelsystemen
            ['id' => 99,  'field_id' => 82,  'field_group_id' => 11, 'form_id' => 1, 'position' => 83,  'required' => 0],
            ['id' => 100, 'field_id' => 83,  'field_group_id' => 11, 'form_id' => 1, 'position' => 84,  'required' => 0],
            ['id' => 103, 'field_id' => 86,  'field_group_id' => 11, 'form_id' => 1, 'position' => 85,  'required' => 0],
            ['id' => 107, 'field_id' => 90,  'field_group_id' => 11, 'form_id' => 1, 'position' => 86,  'required' => 0],
            ['id' => 109, 'field_id' => 92,  'field_group_id' => 11, 'form_id' => 1, 'position' => 87,  'required' => 0],
            ['id' => 151, 'field_id' => 134, 'field_group_id' => 11, 'form_id' => 1, 'position' => 88,  'required' => 0],
            ['id' => 96,  'field_id' => 79,  'field_group_id' => 11, 'form_id' => 1, 'position' => 89,  'required' => 0],
            ['id' => 97,  'field_id' => 80,  'field_group_id' => 11, 'form_id' => 1, 'position' => 90,  'required' => 0],
            ['id' => 98,  'field_id' => 81,  'field_group_id' => 11, 'form_id' => 1, 'position' => 91,  'required' => 0],
            // Form 1 — Groep 23: Hijshaken en -blokken
            ['id' => 165, 'field_id' => 148, 'field_group_id' => 23, 'form_id' => 1, 'position' => 93,  'required' => 0],
            ['id' => 166, 'field_id' => 149, 'field_group_id' => 23, 'form_id' => 1, 'position' => 94,  'required' => 0],
            ['id' => 161, 'field_id' => 144, 'field_group_id' => 23, 'form_id' => 1, 'position' => 95,  'required' => 0],
            ['id' => 164, 'field_id' => 147, 'field_group_id' => 23, 'form_id' => 1, 'position' => 96,  'required' => 0],
            ['id' => 168, 'field_id' => 151, 'field_group_id' => 23, 'form_id' => 1, 'position' => 97,  'required' => 0],
            ['id' => 170, 'field_id' => 153, 'field_group_id' => 23, 'form_id' => 1, 'position' => 98,  'required' => 0],
            ['id' => 171, 'field_id' => 154, 'field_group_id' => 23, 'form_id' => 1, 'position' => 99,  'required' => 0],
            ['id' => 173, 'field_id' => 156, 'field_group_id' => 23, 'form_id' => 1, 'position' => 100, 'required' => 0],
            ['id' => 176, 'field_id' => 159, 'field_group_id' => 23, 'form_id' => 1, 'position' => 101, 'required' => 0],
            // Form 1 — Groep 25: Opstelling / fundatie
            ['id' => 180, 'field_id' => 163, 'field_group_id' => 25, 'form_id' => 1, 'position' => 103, 'required' => 0],
            ['id' => 181, 'field_id' => 164, 'field_group_id' => 25, 'form_id' => 1, 'position' => 104, 'required' => 0],
            ['id' => 182, 'field_id' => 165, 'field_group_id' => 25, 'form_id' => 1, 'position' => 105, 'required' => 0],
            // Form 1 — Groep 27: Afstempeling
            ['id' => 184, 'field_id' => 167, 'field_group_id' => 27, 'form_id' => 1, 'position' => 107, 'required' => 0],
            ['id' => 185, 'field_id' => 168, 'field_group_id' => 27, 'form_id' => 1, 'position' => 108, 'required' => 0],
            // Form 1 — Groep 28: Onder- / bovenwagen
            ['id' => 186, 'field_id' => 169, 'field_group_id' => 28, 'form_id' => 1, 'position' => 110, 'required' => 0],
            ['id' => 187, 'field_id' => 170, 'field_group_id' => 28, 'form_id' => 1, 'position' => 111, 'required' => 0],
            // Form 1 — Groep 29: Railrijwerk / kraanbaan
            ['id' => 194, 'field_id' => 177, 'field_group_id' => 29, 'form_id' => 1, 'position' => 113, 'required' => 0],
            ['id' => 195, 'field_id' => 178, 'field_group_id' => 29, 'form_id' => 1, 'position' => 114, 'required' => 0],
            ['id' => 196, 'field_id' => 179, 'field_group_id' => 29, 'form_id' => 1, 'position' => 115, 'required' => 0],
            ['id' => 198, 'field_id' => 181, 'field_group_id' => 29, 'form_id' => 1, 'position' => 116, 'required' => 0],
            ['id' => 199, 'field_id' => 182, 'field_group_id' => 29, 'form_id' => 1, 'position' => 117, 'required' => 0],
            ['id' => 201, 'field_id' => 184, 'field_group_id' => 29, 'form_id' => 1, 'position' => 118, 'required' => 0],
            ['id' => 202, 'field_id' => 185, 'field_group_id' => 29, 'form_id' => 1, 'position' => 119, 'required' => 0],
            ['id' => 203, 'field_id' => 186, 'field_group_id' => 29, 'form_id' => 1, 'position' => 120, 'required' => 0],
            ['id' => 204, 'field_id' => 187, 'field_group_id' => 29, 'form_id' => 1, 'position' => 121, 'required' => 0],
            ['id' => 205, 'field_id' => 188, 'field_group_id' => 29, 'form_id' => 1, 'position' => 122, 'required' => 0],
            ['id' => 206, 'field_id' => 189, 'field_group_id' => 29, 'form_id' => 1, 'position' => 123, 'required' => 0],
            ['id' => 207, 'field_id' => 190, 'field_group_id' => 29, 'form_id' => 1, 'position' => 124, 'required' => 0],
            ['id' => 208, 'field_id' => 191, 'field_group_id' => 29, 'form_id' => 1, 'position' => 125, 'required' => 0],
            // Form 1 — Groep 32: Elektrische installatie
            ['id' => 210, 'field_id' => 193, 'field_group_id' => 32, 'form_id' => 1, 'position' => 127, 'required' => 0],
            ['id' => 211, 'field_id' => 194, 'field_group_id' => 32, 'form_id' => 1, 'position' => 128, 'required' => 0],
            ['id' => 212, 'field_id' => 195, 'field_group_id' => 32, 'form_id' => 1, 'position' => 129, 'required' => 0],
            ['id' => 213, 'field_id' => 196, 'field_group_id' => 32, 'form_id' => 1, 'position' => 130, 'required' => 0],
            ['id' => 215, 'field_id' => 198, 'field_group_id' => 32, 'form_id' => 1, 'position' => 131, 'required' => 0],
            ['id' => 214, 'field_id' => 197, 'field_group_id' => 32, 'form_id' => 1, 'position' => 132, 'required' => 0],
            ['id' => 216, 'field_id' => 199, 'field_group_id' => 32, 'form_id' => 1, 'position' => 133, 'required' => 0],
            ['id' => 217, 'field_id' => 200, 'field_group_id' => 32, 'form_id' => 1, 'position' => 134, 'required' => 0],
            // Form 1 — Groep 33: Hydraulische installatie
            ['id' => 218, 'field_id' => 201, 'field_group_id' => 33, 'form_id' => 1, 'position' => 136, 'required' => 0],
            ['id' => 219, 'field_id' => 202, 'field_group_id' => 33, 'form_id' => 1, 'position' => 137, 'required' => 0],
            ['id' => 220, 'field_id' => 203, 'field_group_id' => 33, 'form_id' => 1, 'position' => 138, 'required' => 0],
            ['id' => 221, 'field_id' => 204, 'field_group_id' => 33, 'form_id' => 1, 'position' => 139, 'required' => 0],
            // Form 1 — Groep 34: Diversen
            ['id' => 222, 'field_id' => 205, 'field_group_id' => 34, 'form_id' => 1, 'position' => 141, 'required' => 0],
            // Form 1 — Groep 36: Opschriften
            ['id' => 223, 'field_id' => 206, 'field_group_id' => 36, 'form_id' => 1, 'position' => 143, 'required' => 0],
            ['id' => 224, 'field_id' => 207, 'field_group_id' => 36, 'form_id' => 1, 'position' => 144, 'required' => 0],
            ['id' => 225, 'field_id' => 208, 'field_group_id' => 36, 'form_id' => 1, 'position' => 145, 'required' => 0],
            ['id' => 226, 'field_id' => 209, 'field_group_id' => 36, 'form_id' => 1, 'position' => 146, 'required' => 0],
            // Form 1 — Groep 35: Automatische begrenzers, beveiligingen, signaleringen
            ['id' => 227, 'field_id' => 210, 'field_group_id' => 35, 'form_id' => 1, 'position' => 148, 'required' => 0],
            ['id' => 228, 'field_id' => 211, 'field_group_id' => 35, 'form_id' => 1, 'position' => 149, 'required' => 0],
            ['id' => 229, 'field_id' => 212, 'field_group_id' => 35, 'form_id' => 1, 'position' => 150, 'required' => 0],
            ['id' => 230, 'field_id' => 213, 'field_group_id' => 35, 'form_id' => 1, 'position' => 151, 'required' => 0],
            ['id' => 231, 'field_id' => 214, 'field_group_id' => 35, 'form_id' => 1, 'position' => 152, 'required' => 0],
            ['id' => 232, 'field_id' => 215, 'field_group_id' => 35, 'form_id' => 1, 'position' => 153, 'required' => 0],
            ['id' => 233, 'field_id' => 216, 'field_group_id' => 35, 'form_id' => 1, 'position' => 154, 'required' => 0],
            ['id' => 234, 'field_id' => 217, 'field_group_id' => 35, 'form_id' => 1, 'position' => 155, 'required' => 0],
            ['id' => 235, 'field_id' => 218, 'field_group_id' => 35, 'form_id' => 1, 'position' => 156, 'required' => 0],
            // Form 1 — Groep 37: Bedrijfslastbegrenzer
            ['id' => 236, 'field_id' => 219, 'field_group_id' => 37, 'form_id' => 1, 'position' => 158, 'required' => 0],
            ['id' => 237, 'field_id' => 220, 'field_group_id' => 37, 'form_id' => 1, 'position' => 159, 'required' => 0],
            ['id' => 238, 'field_id' => 221, 'field_group_id' => 37, 'form_id' => 1, 'position' => 160, 'required' => 0],
            // Form 1 — Groep 38: Bedrijfslastaanwijzer
            ['id' => 239, 'field_id' => 222, 'field_group_id' => 38, 'form_id' => 1, 'position' => 162, 'required' => 0],
            ['id' => 240, 'field_id' => 223, 'field_group_id' => 38, 'form_id' => 1, 'position' => 163, 'required' => 0],
            ['id' => 241, 'field_id' => 224, 'field_group_id' => 38, 'form_id' => 1, 'position' => 164, 'required' => 0],
            ['id' => 242, 'field_id' => 225, 'field_group_id' => 38, 'form_id' => 1, 'position' => 165, 'required' => 0],
            ['id' => 243, 'field_id' => 226, 'field_group_id' => 38, 'form_id' => 1, 'position' => 166, 'required' => 0],
            // Form 1 — Groep 39: Overige opmerkingen
            ['id' => 244, 'field_id' => 227, 'field_group_id' => 39, 'form_id' => 1, 'position' => 168, 'required' => 0],
            // Form 2 — Groep 12: Algemeen
            ['id' => 101, 'field_id' => 84,  'field_group_id' => 12, 'form_id' => 2, 'position' => 2,   'required' => 0],
            ['id' => 102, 'field_id' => 85,  'field_group_id' => 12, 'form_id' => 2, 'position' => 3,   'required' => 0],
            ['id' => 104, 'field_id' => 87,  'field_group_id' => 12, 'form_id' => 2, 'position' => 4,   'required' => 0],
            ['id' => 105, 'field_id' => 88,  'field_group_id' => 12, 'form_id' => 2, 'position' => 5,   'required' => 0],
            ['id' => 106, 'field_id' => 89,  'field_group_id' => 12, 'form_id' => 2, 'position' => 6,   'required' => 0],
            // Form 2 — Groep 13: Toegangen / bordessen
            ['id' => 108, 'field_id' => 91,  'field_group_id' => 13, 'form_id' => 2, 'position' => 8,   'required' => 0],
            ['id' => 110, 'field_id' => 93,  'field_group_id' => 13, 'form_id' => 2, 'position' => 9,   'required' => 0],
            ['id' => 111, 'field_id' => 94,  'field_group_id' => 13, 'form_id' => 2, 'position' => 10,  'required' => 0],
            ['id' => 112, 'field_id' => 95,  'field_group_id' => 13, 'form_id' => 2, 'position' => 11,  'required' => 0],
            // Form 2 — Groep 14: Bedieningsplaatsen
            ['id' => 113, 'field_id' => 96,  'field_group_id' => 14, 'form_id' => 2, 'position' => 13,  'required' => 0],
            ['id' => 114, 'field_id' => 97,  'field_group_id' => 14, 'form_id' => 2, 'position' => 14,  'required' => 0],
            ['id' => 115, 'field_id' => 98,  'field_group_id' => 14, 'form_id' => 2, 'position' => 15,  'required' => 0],
            ['id' => 116, 'field_id' => 99,  'field_group_id' => 14, 'form_id' => 2, 'position' => 16,  'required' => 0],
            ['id' => 117, 'field_id' => 100, 'field_group_id' => 14, 'form_id' => 2, 'position' => 17,  'required' => 0],
            // Form 2 — Groep 15: Mast / geleiding
            ['id' => 118, 'field_id' => 101, 'field_group_id' => 15, 'form_id' => 2, 'position' => 19,  'required' => 0],
            ['id' => 119, 'field_id' => 102, 'field_group_id' => 15, 'form_id' => 2, 'position' => 20,  'required' => 0],
            ['id' => 120, 'field_id' => 103, 'field_group_id' => 15, 'form_id' => 2, 'position' => 21,  'required' => 0],
            ['id' => 121, 'field_id' => 104, 'field_group_id' => 15, 'form_id' => 2, 'position' => 22,  'required' => 0],
            ['id' => 122, 'field_id' => 105, 'field_group_id' => 15, 'form_id' => 2, 'position' => 23,  'required' => 0],
            ['id' => 123, 'field_id' => 106, 'field_group_id' => 15, 'form_id' => 2, 'position' => 24,  'required' => 0],
            // Form 2 — Groep 16: Onder / bovenstation
            ['id' => 124, 'field_id' => 107, 'field_group_id' => 16, 'form_id' => 2, 'position' => 26,  'required' => 0],
            ['id' => 125, 'field_id' => 108, 'field_group_id' => 16, 'form_id' => 2, 'position' => 27,  'required' => 0],
            ['id' => 126, 'field_id' => 109, 'field_group_id' => 16, 'form_id' => 2, 'position' => 28,  'required' => 0],
            ['id' => 127, 'field_id' => 110, 'field_group_id' => 16, 'form_id' => 2, 'position' => 29,  'required' => 0],
            // Form 2 — Groep 17: Liftkooi
            ['id' => 128, 'field_id' => 111, 'field_group_id' => 17, 'form_id' => 2, 'position' => 31,  'required' => 0],
            ['id' => 129, 'field_id' => 112, 'field_group_id' => 17, 'form_id' => 2, 'position' => 32,  'required' => 0],
            ['id' => 130, 'field_id' => 113, 'field_group_id' => 17, 'form_id' => 2, 'position' => 33,  'required' => 0],
            ['id' => 131, 'field_id' => 114, 'field_group_id' => 17, 'form_id' => 2, 'position' => 34,  'required' => 0],
            ['id' => 132, 'field_id' => 115, 'field_group_id' => 17, 'form_id' => 2, 'position' => 35,  'required' => 0],
            ['id' => 133, 'field_id' => 116, 'field_group_id' => 17, 'form_id' => 2, 'position' => 36,  'required' => 0],
            ['id' => 134, 'field_id' => 117, 'field_group_id' => 17, 'form_id' => 2, 'position' => 37,  'required' => 0],
            ['id' => 135, 'field_id' => 118, 'field_group_id' => 17, 'form_id' => 2, 'position' => 38,  'required' => 0],
            ['id' => 136, 'field_id' => 119, 'field_group_id' => 17, 'form_id' => 2, 'position' => 39,  'required' => 0],
            ['id' => 137, 'field_id' => 120, 'field_group_id' => 17, 'form_id' => 2, 'position' => 40,  'required' => 0],
            ['id' => 138, 'field_id' => 121, 'field_group_id' => 17, 'form_id' => 2, 'position' => 41,  'required' => 0],
            // Form 2 — Groep 18: Elektrische installatie
            ['id' => 139, 'field_id' => 122, 'field_group_id' => 18, 'form_id' => 2, 'position' => 43,  'required' => 0],
            ['id' => 140, 'field_id' => 123, 'field_group_id' => 18, 'form_id' => 2, 'position' => 44,  'required' => 0],
            ['id' => 141, 'field_id' => 124, 'field_group_id' => 18, 'form_id' => 2, 'position' => 45,  'required' => 0],
            ['id' => 142, 'field_id' => 125, 'field_group_id' => 18, 'form_id' => 2, 'position' => 46,  'required' => 0],
            ['id' => 143, 'field_id' => 126, 'field_group_id' => 18, 'form_id' => 2, 'position' => 47,  'required' => 0],
            ['id' => 144, 'field_id' => 127, 'field_group_id' => 18, 'form_id' => 2, 'position' => 48,  'required' => 0],
            // Form 2 — Groep 19: Drijfwerk / rondsel / tandheugel
            ['id' => 145, 'field_id' => 128, 'field_group_id' => 19, 'form_id' => 2, 'position' => 50,  'required' => 0],
            ['id' => 146, 'field_id' => 129, 'field_group_id' => 19, 'form_id' => 2, 'position' => 51,  'required' => 0],
            ['id' => 147, 'field_id' => 130, 'field_group_id' => 19, 'form_id' => 2, 'position' => 52,  'required' => 0],
            ['id' => 148, 'field_id' => 131, 'field_group_id' => 19, 'form_id' => 2, 'position' => 53,  'required' => 0],
            ['id' => 149, 'field_id' => 132, 'field_group_id' => 19, 'form_id' => 2, 'position' => 54,  'required' => 0],
            ['id' => 150, 'field_id' => 133, 'field_group_id' => 19, 'form_id' => 2, 'position' => 55,  'required' => 0],
            // Form 2 — Groep 21: Staalkabels
            ['id' => 152, 'field_id' => 135, 'field_group_id' => 21, 'form_id' => 2, 'position' => 57,  'required' => 0],
            ['id' => 153, 'field_id' => 136, 'field_group_id' => 21, 'form_id' => 2, 'position' => 58,  'required' => 0],
            ['id' => 154, 'field_id' => 137, 'field_group_id' => 21, 'form_id' => 2, 'position' => 59,  'required' => 0],
            ['id' => 155, 'field_id' => 138, 'field_group_id' => 21, 'form_id' => 2, 'position' => 60,  'required' => 0],
            ['id' => 156, 'field_id' => 139, 'field_group_id' => 21, 'form_id' => 2, 'position' => 61,  'required' => 0],
            ['id' => 157, 'field_id' => 140, 'field_group_id' => 21, 'form_id' => 2, 'position' => 62,  'required' => 0],
            // Form 2 — Groep 22: Opschriften
            ['id' => 158, 'field_id' => 141, 'field_group_id' => 22, 'form_id' => 2, 'position' => 64,  'required' => 0],
            ['id' => 159, 'field_id' => 142, 'field_group_id' => 22, 'form_id' => 2, 'position' => 65,  'required' => 0],
            ['id' => 160, 'field_id' => 143, 'field_group_id' => 22, 'form_id' => 2, 'position' => 66,  'required' => 0],
            ['id' => 162, 'field_id' => 145, 'field_group_id' => 22, 'form_id' => 2, 'position' => 67,  'required' => 0],
            ['id' => 163, 'field_id' => 146, 'field_group_id' => 22, 'form_id' => 2, 'position' => 68,  'required' => 0],
            // Form 2 — Groep 24: Veiligheidsinrichtingen
            ['id' => 167, 'field_id' => 150, 'field_group_id' => 24, 'form_id' => 2, 'position' => 70,  'required' => 0],
            ['id' => 169, 'field_id' => 152, 'field_group_id' => 24, 'form_id' => 2, 'position' => 71,  'required' => 0],
            ['id' => 172, 'field_id' => 155, 'field_group_id' => 24, 'form_id' => 2, 'position' => 72,  'required' => 0],
            ['id' => 174, 'field_id' => 157, 'field_group_id' => 24, 'form_id' => 2, 'position' => 73,  'required' => 0],
            ['id' => 175, 'field_id' => 158, 'field_group_id' => 24, 'form_id' => 2, 'position' => 74,  'required' => 0],
            ['id' => 177, 'field_id' => 160, 'field_group_id' => 24, 'form_id' => 2, 'position' => 75,  'required' => 0],
            ['id' => 178, 'field_id' => 161, 'field_group_id' => 24, 'form_id' => 2, 'position' => 76,  'required' => 0],
            ['id' => 179, 'field_id' => 162, 'field_group_id' => 24, 'form_id' => 2, 'position' => 77,  'required' => 0],
            // Form 2 — Groep 26: Beproeving
            ['id' => 183, 'field_id' => 166, 'field_group_id' => 26, 'form_id' => 2, 'position' => 79,  'required' => 0],
            ['id' => 188, 'field_id' => 171, 'field_group_id' => 26, 'form_id' => 2, 'position' => 80,  'required' => 0],
            ['id' => 189, 'field_id' => 172, 'field_group_id' => 26, 'form_id' => 2, 'position' => 81,  'required' => 0],
            ['id' => 190, 'field_id' => 173, 'field_group_id' => 26, 'form_id' => 2, 'position' => 82,  'required' => 0],
            ['id' => 191, 'field_id' => 174, 'field_group_id' => 26, 'form_id' => 2, 'position' => 83,  'required' => 0],
            ['id' => 192, 'field_id' => 175, 'field_group_id' => 26, 'form_id' => 2, 'position' => 84,  'required' => 0],
            ['id' => 193, 'field_id' => 176, 'field_group_id' => 26, 'form_id' => 2, 'position' => 85,  'required' => 0],
            // Form 2 — Groep 30: Toelichting tekortkomingen
            ['id' => 197, 'field_id' => 180, 'field_group_id' => 30, 'form_id' => 2, 'position' => 87,  'required' => 0],
            ['id' => 200, 'field_id' => 183, 'field_group_id' => 30, 'form_id' => 2, 'position' => 88,  'required' => 0],
            // Form 2 — Groep 31: Overige opmerkingen
            ['id' => 209, 'field_id' => 192, 'field_group_id' => 31, 'form_id' => 2, 'position' => 90,  'required' => 0],
        ], ['id'], ['field_id', 'field_group_id', 'form_id', 'position', 'required']);
    }
}
